import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Config from '@/components/Config';
import LoadingAnimation from '@/components/LoadingAnimation';

const font = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='pl'>
			<body className={`${font.className} bg-light text-light-content dark:bg-dark dark:text-dark-content `}>
				<LoadingAnimation />
				<Config>{children}</Config>
			</body>
		</html>
	);
}
